version: "3.8"
services:
  priorizacao:
    build: .
    ports:
      - "127.0.0.1:8090:80"
    volumes:
      - ./:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - bora-network


networks:
  bora-network:
    external: true